apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: default
stringData:
  host: "amqp://admin:admin!@rabbitmq.rabbitmq-system.svc.cluster.local:5672/"
  queueName: request-topic
