apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: producer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: producer.main
    packageref:
      name: producer-pkg
      namespace: default
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: keda-rabbitmq-secret
    namespace: default
