include:
- producer.zip
kind: ArchiveUploadSpec
name: producer-zip-pNGT

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: producer-pkg
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://producer-zip-pNGT
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-03-31T15:51:50Z"
