include:
- consumer.zip
kind: ArchiveUploadSpec
name: consumer-zip-YQa0

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: consumer-pkg
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://consumer-zip-YQa0
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-03-31T15:51:30Z"
